<?php
$pageTitle       = 'Unicismo | Doutrina — Assembleia Cristã Jardim do Mar';
$pageDescription = 'O Unicismo — a doutrina bíblica que afirma que Deus é absolutamente Um, manifestado como Pai, Filho e Espírito Santo.';
$assetsPath      = '../';
$rootPath        = '../';
include_once __DIR__ . '/../includes/header.php';

$article = [
    'title'      => 'Fundamentos da Crença',
    'hero_img'   => '../assets/images/unicismo.png',
    'banner_img' => '../assets/images/unicismo.png',
    'body'       => '
<p>As Santas Escrituras são a única fonte, o fundamento perfeito e o único fio de prumo da fé, dos ensinamentos e da vida. Deus, através de seus profetas no Velho Testamento e dos apóstolos no Novo Testamento, disse tudo que nós necessitamos saber. A Bíblia é o testemunho completo de Deus, à qual, como no caso de um testamento, nada pode ser adicionado.</p>
<p>A Missão Popular Livre Krefeld se diferencia de todos os movimentos de reavivamento que a Igreja de Cristo experimentou desde a época da Reforma Religiosa. Todos fundaram suas próprias igrejas e organizaram-se nas respectivas e bem conhecidas denominações. Através da proclamação da Palavra revelada, nós anunciamos a plena vontade de Deus, que é necessária para a conclusão do plano divino. É nosso alvo servir a todo o povo de Deus em todas as igrejas, independente da confissão ou denominação. Desta proclamação não surgem novamente denominações, eventualmente submissas à obra missionária de Krefeld, mas sim o resultado deve ser e será a Igreja Noiva preparada de Jesus Cristo que Ele mesmo está chamando de todos os lugares.</p>
<p>Nós de modo algum reivindicamos qualquer direito exclusivo para a salvação, mas vemo-nos como parte da comunidade ou igreja de cristãos »Ecclesia«, chamada para fora e eleita através da Palavra de Deus, formando a Igreja viva do Deus vivo. Esta não aponta nenhum homem como fundador, mas na realidade é pelo Espírito de Deus uma continuação e a seqüência dos últimos reavivamentos com o fim de que o SENHOR, Ele mesmo, construa e conclua Sua própria Igreja.</p>
<p>A proclamação da Palavra de Deus em ligação com o eternamente válido Evangelho de Jesus Cristo tem sempre um duplo efeito segundo as Santas Escrituras: primeiramente é mostrado diante dos nossos olhos o juízo, o legítimo julgamento devido a todas as transgressões das leis que nós seres humanos perdidos cometemos. O outro ponto é a fé, vinda da pregação da Palavra, a força divina que causa a salvação da alma e a completa justificação diante de Deus daqueles que se sujeitam ao Seu julgamento.</p>
<p>Entretanto, a justificação do pecador não significa a justificação do pecado. Somente aqueles que aceitam pessoalmente a oferta de Graça de Deus, podem vivenciar a Salvação e confirmar terem sido chamados e eleitos por Deus. Quem rejeitar também será rejeitado; quem não aceitar também não será aceito por Ele.</p>
<p>A Santa Escritura é inequívoca e univalente em tudo que afirma. Somente o que é dito sobre Ela tem vários sentidos, dando margem à interpretações. Por este motivo, pelo amor à verdade revelada da Palavra de Deus, nós rejeitamos definitivamente toda e qualquer interpretação.</p>
<p>Apenas o que os apóstolos deixaram escrito no Novo Testamento é, de fato, »doutrina ou ensinamento apostólico«. Somente o que foi verdadeiramente atestado na Bíblia é »bíblico«. Somente o que é original de Cristo é »cristão«. As decisões de concílios religiosos tomadas no curso da história da igreja rejeitamos como adições e falsificações da Palavra Original.</p>
<p>A fé no único e verdadeiro Deus, além do qual não há outro, e que se revela para nós em Sua diversidade como Criador, Mantenedor, Salvador, Rei, Juiz, etc., é o único e obrigatório fundamento da nossa crença.</p>
<p>Rejeitamos inteiramente o credo da Nicéia-Calcedônia como não bíblico. Deste podemos ler entre outros trechos, como segue: »... filho único de Deus, que nasceu do Pai diante de todo o mundo, Deus de Deus, luz da luz, verdadeiro Deus do Deus verdadeiro, nascido, não criado, um ser com o Pai...«. Não há em nenhum lugar da Bíblia versículo ou vaga indicação do nascimento do filho ocorrido no Céu, que o Pai tenha dado à luz. O Filho nasceu aqui na terra como descrito nos evangelhos. O verdadeiro credo apostólico é encontrado unicamente na Bíblia. Na história dos dogmas são encontrados apenas credos e doutrinas de igrejas.Deus é único. Não há três onipresentes, não há três eternos e oniscientes, não há três que dividem a autoridade e soberania absoluta entre eles, não há três que se unem, mas sim, existe somente o único, Todo-Poderoso e eterno Deus, que desde o começo dos tempos se manifestou, Ele mesmo, de diversas maneiras. No Novo Testamento, na Nova Aliança, Ele se revelou para nossa salvação como Pai no Céu, no Filho como Emanuel = »Deus conosco« e através do Espírito Santo. O »Filho« foi anunciado em todo o Velho Testamento. Ele é o concebido pelo Espírito Santo, que nasceu de Maria, o Redentor que veio em carne, o »Primogênito« entre muitos irmãos. Com Seu sofrimento e morte no nosso lugar, todos os filhos e filhas de Deus foram reconciliados com seu Pai Celestial. Com a pregação do Evangelho de Jesus Cristo desejamos trazer às pessoas o plano de salvação de Deus, para que possam vivenciar sua própria experiência de salvação. Assim o ser humano experimenta a sua conversão – uma mudança de mentalidade e atitude – na qual ele abandona o largo caminho da perdição, é renovado no seu coração e renasce através da Palavra e do Espírito de Deus como uma viva esperança.</p>
<p>Deus criou o homem à sua própria imagem para viver em comunhão com Ele. O relacionamento entre o Criador e o ser humano criado por Ele foi quebrado com a queda no pecado.</p>
<p>A queda no pecado resultou na sedução, da qual então surgiu uma semente. Por isto, diretamente após a queda, o SENHOR teve que pôr inimizade entre estas duas sementes distintas e condenar Eva para dar à luz aos seus filhos com dores de parto.</p>
<p>No mesmo contexto foi dada a primeira promessa com vista à vinda do Messias, que viria como »semente divina« através da mulher e esmagaria então a amaldiçoada cabeça da serpente.</p>
<p>No início da criação natural, Satanás lançou a humanidade no pecado através da sedução de Eva e da transgressão de Adão ganhando desta forma influência e poder sobre toda a criação. Esta estava agora separada de Deus através da desobediência e transgressão e, assim, condenada à morte.</p>
<p>No começo da criação sobrenatural, Deus, através do segundo Adão, arrebatou de Satanás a humanidade caída. Maria foi visitada pelo Espírito Santo e assim nasceu o Filho de Deus, pela concepção do Espírito, para reparar o dano através da Redenção e Reconciliação e restabelecer desta maneira novamente a comunhão com Deus.</p>
<p>O mistério da Redenção da humanidade perdida consiste do fato de que o Redentor mesmo, que era no princípio a Palavra, tornou-se carne, completamente humano, para sofrer e morrer no corpo carnal e vencer através da ressurreição a morte e o inferno. Porque a queda no pecado ocorreu na carne e no sangue tornou-se necessário que a redenção da humanidade caída também se realizasse pelo Redentor no Seu corpo carnal. Dele verteu na cruz do Calvário o Seu Santo sangue, no qual havia vida divina para a nossa redenção.</p>
<p>Assim, apesar desta breve interrupção temporal, a vontade inalterável de Deus segue adiante o seu curso até Sua conclusão para toda a eternidade, com todas as pessoas que aceitaram a Sua oferta de Graça. Em plena bem-aventurança todos estes entrarão na eterna Glória Celestial. Após a conclusão do plano de salvação divino o tempo afluirá na eternidade.</p>
',
];

include_once __DIR__ . '/_article_template.php';
include_once __DIR__ . '/../includes/footer.php';
?>
